sudo: required
services:
  - docker

before_install:
  - docker build -t naenaenae/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true naenaenae/react-test npm test

after_success:
  - docker build -t naenaenae/multi-client ./client
  - docker build -t naenaenae/multi-nginx ./nginx
  - docker build -t naenaenae/multi-server ./server
  - docker build -t naenaenae/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push naenaenae/multi-client
  - docker push naenaenae/multi-nginx
  - docker push naenaenae/multi-server
  - docker push naenaenae/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-994676419963
  bucket_path: docker-multi
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY

language: generic
